### PR TITLE
fix: file provisioner does not transfer folders

### LINKED ISSUE #31: File provisioner does not transfer folders
In this example,

`
provisioner "file" {
  sources = [ "srcfolder/foo" ] destination = "dstfolder"
}
`

files are copied in "dstfolder" instead of "dstfolder/foo".

### PR DESCRIPTION
**Pull request by devashish-patel**
- The upload directory function currently adds `/.` at the end of the `source` path, which changes the behavior of the `cp`. 
- The change in this PR relies on the user input if the source ends with `/.` we only copy the content of the directory otherwise the while source directory to the destination.

Resolves #31

### CODE REVIEW

**Review by sylviamoss — APPROVED** [review]
Nice catch!

File: builder/lxc/communicator.go [hunk 1]
```diff
@@ -105,7 +105,7 @@ func (c *LxcAttachCommunicator) UploadDir(dst string, src string, exclude []stri
 	// TODO: remove any file copied if it appears in `exclude`
 	dest := filepath.Join(c.RootFs, dst)
 	log.Printf("Uploading directory '%s' to rootfs '%s'", src, dest)
-	cpCmd, err := c.CmdWrapper(fmt.Sprintf("cp -R %s/. %s", src, dest))
+	cpCmd, err := c.CmdWrapper(fmt.Sprintf("cp -R %s %s", src, dest))
```
Comment (nywilken) [inline builder/lxc/communicator.go:108]: According to the docs if the source path contains a trailing slash on the contents of the directory will get uploaded on to the container. Requiring the user to include a trailing slash-dot `/.` changes the expected behavior. 

Suggested change
```go
// Source directories with a trailing slash should only copy the contents of the directory
if strings.HasSuffix(src, "/") {
  src = fmt.Sprintf("%s/.",src)
}
cpCmd, err := c.CmdWrapper(fmt.Sprintf("cp -R %s %s", src, dest))
```

**Review by nywilken — CHANGES_REQUESTED** [review]
This changes the documented behavior for the file provisioner when running on lxc. With this change source directories with the trailing slash copies the parent source directory along with its contents. But it should only copy the contents.

**Review by nywilken — APPROVED** [review]
Nicely done. The changes look good.
